### ISSUE TITLE
polyfit?

### ISSUE THREAD

**Issue by ggggggggg** [Keno/Polynomials.jl#19]
I'd like to see a `polyfit` function somewhere in the julia ecosystem, is this the right place?

Something like
```
julia> function polyfit(x, y, n)
         A = [ float(x[i])^p for i = 1:length(x), p = 0:n ]
         Poly(A \ y)
       end
polyfit (generic function with 1 method)
julia> x = [0:10];
julia> y = x.^2-15*x+50;
julia> p=polyfit(x,y,2)
Poly(49.99999999999998 - 14.999999999999991x + 0.9999999999999991x^2)
```

**Comment by MTornen** [comment]
I have the same comment, maybe some sort of merger between CurveFit.jl and Polynomials.jl? CurveFit was giving me some compatibility warnings so downloaded linfit.jl from src and created by own module from it.

**Comment by jverzani** [comment]
This function was just checked in. Thanks!
