### ISSUE TITLE
Variable name is not kept after operations

### ISSUE THREAD

**Issue by ronisbr** [Keno/Polynomials.jl#23]
Hi!
First, thank you for the Polynomials package, it is amazing!

I am having an issue when I change the variable name. It is not being kept after operations. It always return to 'x'. For example:

```julia
julia> a = Poly([1, 1], 's')
Poly(1 + s)

julia> b = Poly([1, 2, 3, 4, 5, 6], 's')
Poly(1 + 2s + 3s^2 + 4s^3 + 5s^4 + 6s^5)

julia> c = a+b
Poly(2 + 3x + 3x^2 + 4x^3 + 5x^4 + 6x^5)

julia> d = a*b
Poly(1 + 3x + 5x^2 + 7x^3 + 9x^4 + 11x^5 + 6x^6)
```

Would it not be better to keep the variable name after operations?

Thanks,
Ronan

**Comment by pwl** [comment]
By chance I fixed this some time ago in my fork.  Take a look at PR #24.
