### ISSUE TITLE
A little love...

### ISSUE THREAD

**Issue by jverzani** [Keno/Polynomials.jl#36]
Hi @keno. This package could use a little love. Here are some things that seem reasonable

* polyfit function: issue #19 
* Common polynomials: issue #33 pull request #18
* add docstrings (basically take from the Readme)
* change `/` to `div`
* devectorise (Pull request #17)

I can add/merge these if they seem like good additions. Some are outside the current scope of the package, but all seem reasonable, to me.

**Comment by Keno** [comment]
Hi @jverzani,

please go ahead and do whatever you think is reasonable. You should already have commit access I think. I'd also be happy to transfer the package to you if you want.

**Comment by jverzani** [comment]
Thanks @keno. I pushed all but the one on common polynomials to master with f796a8c. That last one seems like it can be done easily enough by using the `FastGaussQuadrature` package, which generates the zeros of many families of orthogonal polynomials. Maybe best to leave as an example. As for transferring the package, I don't mind, but I really don't have much in mind to add to this, save maybe writing a notebook of example usage. Whatever works for you. I know you have bigger fish to fry.
