### ISSUE TITLE
Constructor non-intuitive cancellation of small coefficient values

### ISSUE THREAD

**Issue by KlausC** [Keno/Polynomials.jl#38]
The main constructor contains the 3 lines:
```
# determine the last nonzero element and truncate a accordingly
a_last = max(1,findlast( p->(abs(p) > 2*eps(T)), a))
new(a[1:a_last], symbol(var))
```
That has a surprising consequence:
All higher coefficients are truncated, if their absolute value is below eps(). That generates an underflow-behaviour at high values. It would be easy to find `p=Poly(..); p / 1000 * 1000 != p`. There should be no such limitation, which restricts usability, for example when working with interpolating polynomials of higher degrees.

I recommend to replace `abs(p) > eps(T)` by `p != zero(T)`

**Comment by jverzani** [comment]
I believe this is the case for T an integer or rational type. Can you use those?

**Comment by pwl** [comment]
I kind of agree with point 1.  If we are to keep the smallness condition it should be relative to other coefficients, not an absolute value like it is now.  The tests were all positive with
```
# a_last = max(1,findlast( p->(abs(p) > 2*eps(T)), a))
a_last = max(1,findlast(a))
```
but maybe I am missing some edge cases.

As for point 2. `a[1:a_last]` always returns a copy of `a` so I cannot reproduce the behavior you described.

**Comment by KlausC** [comment]
jverzani.  I could use high precision or rational or integer arthmetic, of couse, but my problem is in the Float64 case, where eps ~ 2e-16.
pwl. Your are right with issue 2, which I removed already in the original comment.
I have here some test cases, which show the bad useability.
T1: I would expect to be  p(x) * a != 0 if p(x) != 0 and a != 0, but   Poly([0.0, 2e-8]) * 2e-8 == Poly(0.0).
T2: Imagine I want to interpolate at 5 points x the values y by a polynomial of degree 4. I try pf = polyfit(float([0:4]*1e4, [1, 0, 0, 0, 0]); but degree(pf) == 4 is false. Reason is that Poly cannot represent the highest coefficient, which gets below 2eps(). There would be a workaround by scaling x, but that is absolutely not necessary, because Float64 is capable of representing 1e-308.
With the same argument as forbidding higher coefficients below eps() it would be justified to set all results of floating point scalar operations to zero, if they are below eps() in absolute value ...

I would suggest to let the user decide, if he wants coefficients to be truncated by introducing a new utility function like polytruncate(p::Poly, tolerance) ... and in the normal case only remove exact zero.

**Comment by jverzani** [comment]
There are arguments for or against. If you change the internal definition of `eps` to `eps{F<:AbstractFloat}(x::Type{F}) = Base.zero(F) `, then you get what you want. However, this means simple polynomial operations can go askew: 

```
p = Poly([1,1]/10)
q = Poly([1,2]/10)
r = Poly([1,3]/10)
p + q - r  ## will have wrong degree
```

I don't see an easy way to let the user specify what is used for eps, but if you do, and it doesn't impact performance you should put together a pull request.

**Comment by vtjnash** [comment]
I believe my original intention was to avoid numeric instability in the evaluation of polynomials, division and root finding from the presence of non-significant leading zeros. `eps(max(coef))` would probably have been a more correct cutoff, so that magnitude scaling didn't affect the result.
