### ISSUE TITLE
`roots` is type unstable

### ISSUE THREAD

**Issue by dpsanders** [Keno/Polynomials.jl#42]
The `roots` function is not type stable, since it can return either `Array{Complex{Float64},1}` or `Array{Float64,1}`, depending only on the polynomial coefficients.

It would seem like a good idea to always return `Array{Complex{Float64},1}`.

**Comment by vtjnash** [comment]
this is intentional (i think there was discussion on the issue list of vtjnash/Polynomial.jl)

**Comment by jverzani** [comment]
I added a brief comment in the README about this "feature."
