### ISSUE TITLE
Very confusing name for poly()

### ISSUE THREAD

**Issue by bunder** [Keno/Polynomials.jl#47]
It is very confusing to see two very similar _almost_ constructors `Poly()` and `poly()` which are quite different. I propose to rename `poly()` so that it will be evident what's it do. For example `byroots()` or `fromroots()` or something similar.

**Comment by jverzani** [comment]
I'm not sure of the history, but `poly` is the function used to construct a "polynomial" in MATLAB. There polynomials are just coefficient vectors. Here `Poly` is the constructor use to create a Polynomial object from such an object. So there is some precedence or the naming convention. As this didn't generate much conversation, I'm going to close it.
