### ISSUE TITLE
`roots` is not type-stable

### ISSUE THREAD

**Issue by aytekinar** [Keno/Polynomials.jl#53]
Try the following code:
```julia
using Polynomials
p1 = Poly([1,2,1])
p2 = Poly([1,2,2])
typeof(p1) == typeof(p2)
typeof(roots(p1)) == typeof(roots(p2))
```
which results in `false`, implying the `roots` function is not type-stable.

**Comment by jverzani** [comment]
See #42

**Comment by yuyichao** [comment]
At least dup of https://github.com/Keno/Polynomials.jl/issues/42

**Comment by aytekinar** [comment]
Not a duplicate, tho. One can have a small change in the code and still have the same precision. I am not talking about the precision whatsoever mentioned in the given link/topic.

**Comment by aytekinar** [comment]
@yuyichao @jverzani , you can check the code (or I can create a PR if you want) for the change. the code change is really small and nothing is lost in terms of precision.
