### ISSUE TITLE
No way of getting the coefficients of the polynomial in a separate vector

### ISSUE THREAD

**Issue by MadDataScientist** [Keno/Polynomials.jl#55]
This seems like the most fundamental feature, yet it is missing. Are you planning to implement this at one point, or should I be looking for a hack to get the coefficients from a Poly object?

**Comment by vtjnash** [comment]
`coeffs(poly)`

**Comment by MadDataScientist** [comment]
Thanks! It would be nice if this was mentioned somewhere in the documentation.

**Comment by pwl** [comment]
Feel free to add the docs yourself if you already figured out how `coeffs` works!

**Comment by jverzani** [comment]
The doc issue should be addressed now.
