### ISSUE TITLE
`conj` works unexpectedly for complex polynomials

### ISSUE THREAD

**Issue by olof3** [Keno/Polynomials.jl#59]
`conj` is defined in `Base` as `conj(x) = x` so

```
julia> using Polynomials; Poly([1, 2 + im])
```
returns
```
Poly(1 + (2 + 1im)x)
```
I guess the standard definition is that the coefficients are simply conjugated.

See  http://math.stackexchange.com/questions/25422/conjugate-of-complex-polynomial for a short discussion

**Comment by jverzani** [comment]
Guess we need a method:

```
Base.conj(p::Poly) = Poly(conj(coeffs(p))) 
```

Care to submit a pull request?
