### ISSUE TITLE
unnecessary copy in convert

### ISSUE THREAD

**Issue by neveritt** [Keno/Polynomials.jl#65]
```
A = Poly([1,2])
B = convert(Poly{Int64}, A)
```
The last expression actually copies A to B. In contrast to, for example,
```
A = [1,2]
B = convert(Array{Int64}, A)
```
where `B` points to the same object as `A`. 

This has implications for containers that contain `Poly` objects parametrized by type `T`:
```
immutable MyContainer{T<:Number}
    p::Poly{T}
end
```
The construction of  `MyContainer` will not be passed by reference but will result in a copy such that in the following code:
```
A = Poly([1,2])
m = MyContainer(A)
```
Here, `m.p` will not point to `A` but to a copy of `A`.

The solution is simply to mimic `AbstractArray` by adding the following convert to the same type: 
```
convert{T}(::Type{Poly{T}}, p::Poly{T}) = p
```

**Comment by pwl** [comment]
This looks reasonable, go ahead and make a PR if you have the time.

**Comment by pwl** [comment]
Thanks!
