### ISSUE TITLE
Add support for `Poly("x")`

### ISSUE THREAD

**Issue by aytekinar** [Keno/Polynomials.jl#71]
### Description

A support for `x = Poly("x")` and `x = Poly(Complex128, "x")` type of construction could be cool.
### Desired Behavior

I am not supporting such an attitude in general, but some people with MATLAB background prefer using:

``` julia
julia> using Polynomials
julia> s = Poly("s")
Poly(s)
julia> p1 = s^5 + s^2 + 3s + 1
Poly(1.0 + 3.0s + s^2 + s^5)
```

I have come across such an attitude in users when using the control toolbox in MATLAB. In our attempt to port such functionality in Julia, we are relying on Polynomials. Hence, I thought I could open an issue here and discuss with you.
### Solution Proposal

Should you be interested in supporting such a feature, please check the PR.

P.S: I have also got rid of the clutter in the constructor. I hope you would like it.

**Comment by jverzani** [comment]
There is "variable" which implements this. But that name isn't the best. It is named so, as it also returns x from a poly in x. Maybe best to decouple and take this as a constructor. If no one objects, that is.
