### ISSUE TITLE
Removal of division operator

### ISSUE THREAD

**Issue by aytekinar** [Keno/Polynomials.jl#84]
Would it be OK if we removed `Base./(p1::Poly, p2::Poly)` overload from the package?

Over the weekend I have tried implementing [`RationalFunctions.jl`](https://github.com/aytekinar/RationalFunctions.jl) in the hope for extending `Polynomials` to support rational functions.

In that package, I am redefining the division operator between `Poly`s. However, Julia issues a warning when doing so, which is not fun. It has been, anyway, deprecated for a while now in `Polynomials`.

**Comment by jverzani** [comment]
seems like a good time to clean it up.
