### ISSUE TITLE
More robust polyfit (patch)

### ISSUE THREAD

**Issue by hrobotron** [Keno/Polynomials.jl#89]
Hello,
during some work I found the results of `polyfit` unnecessarily inaccurate.
I have found out, that lsq system matrix is constructed via x.^n (which supposedly walks through log/exp pow), and also the A\y inversion did not work to expectations, compared to other numerical tools.
So I wrote better version of `polyfit`, see attached patch. Also I attach one test data file, try
`x=readdlm("polyfit_8th_order_test.dat");
p=polyfit(x[:,1], x[:,2], 8);
plot(x[:,2]-p(x[:,1])`
-- a *huge* difference between current (meaningless result) and patched version. (And yes, the 8th order is physical in this data set ;-))

Best regards,
Marek

[jl_polyfit_by_mp.diff.txt](https://github.com/Keno/Polynomials.jl/files/659738/jl_polyfit_by_mp.diff.txt)
[polyfit_8th_order_test.dat.zip](https://github.com/Keno/Polynomials.jl/files/659739/polyfit_8th_order_test.dat.zip)

**Comment by yuyichao** [comment]
Thanks for the contribution but please submit this as a pull request instead.
